### PR TITLE
Fix error handling on modern Rust

### PR DESCRIPTION
**Pull request by MOZGIII**
See https://github.com/rust-lang/rust/pull/79965

### CODE REVIEW

**Review by vtavernier — APPROVED** [review]

**Comment by MOZGIII** [comment]
Mind publishing a new release to the crates.io?

**Comment by vtavernier** [comment]
> Mind publishing a new release to the crates.io?

I'm working on it, this should come in a couple of days. I was away from home and didn't have access to a Windows machine to test the release. I'm planning on updating the CI to run on GitHub Actions since I am not using Travis anymore.

**Comment by MOZGIII** [comment]
Sounds good! I've been using GitHub Actions for CI now for a while, you can check them out at https://github.com/MOZGIII/rebootinto

**Comment by vtavernier** [comment]
@MOZGIII 0.2.2 has been released on crates.io!

**Pull request merged**
